# Generated by Django 6.0.4 on 2026-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_entrega',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
