# Generated by Django 6.0.4 on 2026-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nome_bordado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
