# Generated by Django 6.0.4 on 2026-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_itempedido_cor_itempedido_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='arte',
            field=models.FileField(blank=True, null=True, upload_to='artes/'),
        ),
    ]
