# Generated by Django 6.0.4 on 2026-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_itempedido_arte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Universitário', 'Universitário'), ('Empresarial', 'Empresarial'), ('Personalizado', 'Personalizado')], default='Universitário', max_length=30),
        ),
    ]
