# Generated by Django 6.0.4 on 2026-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_branca',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_marinho',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_preta',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_vinho',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
    ]
