# Generated by Django 6.0.4 on 2026-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_remove_produto_tamanho_itempedido_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_logo',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/logos/', verbose_name='Logo do bordado'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_tamanho',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/tamanhos/', verbose_name='Tabela de tamanhos'),
        ),
    ]
