# Generated by Django 6.0.4 on 2026-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_produto_imagem_logo_produto_imagem_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_amarelo',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_azul',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
    ]
