# Generated by Django 6.0.4 on 2026-06-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_produto_imagem_amarelo_produto_imagem_azul'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_verde',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
    ]
