# Generated by Django 6.0.4 on 2026-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_produto_imagem_verde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem_azul',
            new_name='imagem_amarelo_costas',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_branca_costas',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_marinho_costas',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_preta_costas',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_verde_costas',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_vinho_costas',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/cores/'),
        ),
    ]
