# Generated by Django 6.0.4 on 2026-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_rename_imagem_azul_produto_imagem_amarelo_costas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servico_frete',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
