# Generated by Codex on 2026-07-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_produto_imagem_tamanho_feminino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(blank=True, max_length=20)),
                ('nome_cliente', models.CharField(max_length=120)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('curso', models.CharField(blank=True, max_length=120)),
                ('tamanho', models.CharField(blank=True, max_length=5)),
                ('modelagem', models.CharField(blank=True, max_length=20)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('adicionais', models.TextField(blank=True)),
                ('subtotal_unidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_entrega', models.CharField(blank=True, max_length=50)),
                ('cep_entrega', models.CharField(blank=True, max_length=9)),
                ('frete_descricao', models.CharField(blank=True, max_length=220)),
                ('arte', models.FileField(blank=True, null=True, upload_to='artes/orcamentos/')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto')),
            ],
            options={
                'verbose_name': 'Orcamento personalizado',
                'verbose_name_plural': 'Orcamentos personalizados',
                'ordering': ('-criado_em',),
            },
        ),
    ]
